### ISSUE TITLE
discussion: hello, I am the developer of hare 👋 

### ISSUE THREAD

**Issue by barona-mika-vilpas** [sagan/EBWeb#2]
こんにちは！
私は日本語を自習している者ですが、【晴れ】というWEBアプリを開発しました。
日本語力がまだあんまり自信がありませんので、英語でご案内いたします😅

https://github.com/sp3ctum/hare

Hare is a frontend for EBWEB only. It's actually activated as a plugin to EBWEB (using the Custom JS setting in EBWEB), which is unusual but works 😄 
As I am probably the only user, I have added features that help me study the Japanese language.

Perhaps the most interesting one is that I wrote custom parsers for the dictionary definitions using a parsing technique known as parser generators. By applying the parsers I am able to
- add custom formatting, for example for 大辞泉 which does not have proper line breaks
- allow creating anki cards from the example sentences
<img width="992" alt="image" src="https://github.com/sagan/EBWeb/assets/131751931/71a7ddfe-562c-42b1-9706-2a0a0a2acc87">

Anyway, just wanted to say hi, and also to thank you for building the sakura-paris + EBWEB application. It's been very valuable for me. 😊

**Comment by sagan** [comment]
Hi

The parsers that your app implements are really impressive. I myself am just using simple regexp to convert BBCode to HTML。

I created the site years ago for the same purpose of myself learning Japanese (I was tired of epwing softwares like EBWin4 / EBPocket, which are frustrating in many ways). I made the site public in the hope that it will be useful for some others. And I am grad to see it does did.
