### ISSUE TITLE
请问binary/ebclient有没有详细的介绍资料？

### ISSUE THREAD

**Issue by dongnanyanhai** [sagan/EBWeb#3]
你好，我想写一个类似的字典程序用做浏览器插件，请问能否提供binary/ebclient的介绍资料？

或者，能否直接使用您网站上的接口？

**Comment by sagan** [comment]
ebclient 是我用 C 写的后端程序，代码比较混乱，所以暂时还没有公开。功能就是从 stdin 读取请求，查询 epwing 字典然后输出结果到 stdout。程序里主要用了 [libebu](http://green.ribbon.to/~ikazuhiro/dic/ebu.html) 这个库，文档可以在[这里](https://www.mistys-internet.website/eb/)找到。

网站上的 API 目前没有什么使用限制。

**Comment by dongnanyanhai** [comment]
感谢答复。

我先使用您的接口，目前主要是为了方便自己学习日语，预测不会对网站API有太大的访问压力。

后续如果插件有其他人使用，我再尝试实现ebclient，非常感谢！

**Comment by dongnanyanhai** [comment]
感谢！
