### ISSUE TITLE
请教docker部署，想使用网站的API功能

### ISSUE THREAD

**Issue by meddleless** [sagan/EBWeb#4]
您好，非常感谢您的付出。

我想调用网站API批量查询单词发音，方便自己学习日语。
我尝试用docker部署，镜像编译成功，但是部署失败跑不起来。

请问能否请您用发音辞典为例子，指导一下详细的docker部署步骤呢？
或者，能否请您只恢复网站的API接口，仅保留一本发音辞典。

**Comment by sagan** [comment]
我写了一个简单的[部署文档](https://github.com/sagan/EBWeb/wiki/Deployment)。

**Comment by meddleless** [comment]
棒棒哒，跑起来了，来东京请你吃鸡腿🍗
![1](https://github.com/sagan/EBWeb/assets/165040323/a2788084-9f20-4d86-9f09-83cf63a96898)
![2](https://github.com/sagan/EBWeb/assets/165040323/78b10cfc-417d-4ee9-9407-5cb069fcb4b6)

**Comment by meddleless** [comment]
使用了两天左右，API查询输出很稳定，再次表示感谢。
![1](https://github.com/sagan/EBWeb/assets/165040323/9f484735-25a1-4f8b-9184-687c00e6cafa)
![2](https://github.com/sagan/EBWeb/assets/165040323/e6507532-5c1f-4124-881c-876426008490)
![3](https://github.com/sagan/EBWeb/assets/165040323/edd160de-8eaf-47a5-8313-8ed922780014)


> [Yahoo Japan テキスト解析 Web API](https://developer.yahoo.co.jp/webapi/jlp/) (YAHOO_APPID config)
> [Google Custom Search JSON API](https://developers.google.com/custom-search/v1/overview) (GOOGLE_SEARCH_API_KEY & GOOGLE_SEARCH_API_ENGINE config)

Yahoo API配置后，能顺利使用“日本語形態素の解析”功能。
Google Custom Search JSON API配置后，显示“Googleでの解釈を表示できません（Error: Error: Server return status 500）”，不知道是不是我配置错误。
IBM Watson 语言翻译服务即将下线，也停止新用户注册了，不知道会影响网站的哪些功能。

目前来说，我自用的功能已经完全能满足了，非常感谢。
