### ISSUE TITLE
sudo docker pull: manifest unknown

### ISSUE THREAD

**Issue by andy1li** [sagan/EBWeb#5]
大佬您好，我尝试运行 `sudo docker pull ghcr.io/sagan/ebweb:v1.2.18`

但是出现如下报错：
> v1.2.18: Pulling from sagan/ebweb
manifest unknown

我的系统信息如下：
- aws Asia Pacific (Tokyo) ap-northeast-1
- Ubuntu 24.04 LTS (GNU/Linux 6.8.0-1008-aws x86_64)
- Docker version 26.1.2, build 211e74b

请问您是否有建议我如何进一步调整呢？万分感谢~

**Comment by sagan** [comment]
我重新推送了一次镜像，现在应该可以了。我也不知道这是什么原因。

**Comment by andy1li** [comment]
现在可以啦，再次感谢大佬！🙏🙏

**Comment by andy1li** [comment]
现在可以啦，再次感谢大佬！🙏🙏
